### ISSUE TITLE
Use dosbox-staging instead of regular dosbox

### ISSUE THREAD

**Issue by soredake** [flathub/com.valvesoftware.Steam.CompatibilityTool.Boxtron#4]
https://github.com/dosbox-staging/dosbox-staging

**Comment by gasinvein** [comment]
Is it Boxtron's default?

**Comment by soredake** [comment]
![image](https://user-images.githubusercontent.com/5204968/97870034-0af3bb80-1d1b-11eb-8594-57c6672d7f7c.png)
Boxtron recommends the use of dosbox-staging.
